# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: list the current directory
      run: ls -a
    - name: what is the traget folder?
      run: |
         cd target
         ls -a
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
       username: krish6654
       password: Mohan_3402
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
         push: true
         tags: krish6654/githubtest:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
    
    - name: Image run
      run: docker run -itd --name github -p 8080:8080 krish6654/githubtest:latest 
    - name: Image run
      run: | 
        docker ps -a
        ifconfig
